//Get products
export const GET_PRODUCTS_ACTION = "GET_PRODUCTS_ACTION"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_MYPRODUCTS_SUCCESS = "GET_MYPRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

//Login
export const LOGIN_ACTION = "LOGIN_ACTION"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

//Register
export const REGISTER_ACTION = "REGISTER_ACTION"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

//Add product
export const ADD_PRODUCT_ACTION = 'ADD_PRODUCT_ACTION';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

//Add to Cart
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';